# Generated by Django 3.1.6 on 2021-08-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300)),
                ('copy', models.TextField(max_length=3000)),
                ('logo', models.ImageField(upload_to='')),
                ('url', models.URLField()),
            ],
        ),
    ]
