# Generated by Django 3.1.6 on 2021-08-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='logo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
